### ISSUE TITLE
Crash when using Buy/Sell Max button.

### ISSUE THREAD

**Issue by timroham** [faceofcat/Villager-Market#4]
I've triggered two CTD's tonight when I use the Buy/Sell Max button, I will keep testing to see if the buy single button will also crash or not. If you'd like to see the crash report, I'll gladly throw one up for you.

Thanks.

**Comment by faceofcat** [comment]
sure thing mate... a crash log would surely help.

**Comment by timroham** [comment]
God, I hope I did this correctly...

`<details>
  <summary>Crash Log</summary>
  ---- Minecraft Crash Report ----

WARNING: coremods are present:
  DLFMLCorePlugin (DynamicLights-1.12.1.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 11/25/17 7:42 PM
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$KeyIterator.next(Unknown Source)
	at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:290)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:777)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1815726456 bytes (1731 MB) / 4260102144 bytes (4062 MB) up to 4260102144 bytes (4062 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -Xms4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.1.2554 Optifine OptiFine_1.12.2_HD_U_C6 42 mods loaded, 42 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                          | Version      | Source                                   | Signature                                |
	|:--------- |:--------------------------- |:------------ |:---------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                   | 1.12.2       | minecraft.jar                            | None                                     |
	| UCHIJAAAA | mcp                         | 9.42         | minecraft.jar                            | None                                     |
	| UCHIJAAAA | FML                         | 8.0.99.99    | forge-1.12.2-14.23.1.2554.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                       | 14.23.1.2554 | forge-1.12.2-14.23.1.2554.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | mercurius_updater           | 1.0          | MercuriusUpdater-1.12.2.jar              | None                                     |
	| UCHIJAAAA | movillages                  | 1.5.4        | [1.12]MoVillages-1.5.4.jar               | None                                     |
	| UCHIJAAAA | alt                         | 2.0.2        | AdditionalLootTables-1.12.1-2.0.2.29.jar | None                                     |
	| UCHIJAAAA | veinminer                   | 0.38.1       | VeinMiner-1.12-0.38.1.639+134fb1e.jar    | None                                     |
	| UCHIJAAAA | basemetals                  | 2.5.0-beta3  | BaseMetals-1.12-2.5.0-beta3.51.jar       | None                                     |
	| UCHIJAAAA | baseminerals                | 2.5.0-beta2  | BaseMinerals-1.12-2.5.0-beta2.11.jar     | None                                     |
	| UCHIJAAAA | cookingforblockheads        | 6.3.6        | CookingForBlockheads_1.12.1-6.3.6.jar    | None                                     |
	| UCHIJAAAA | cxlibrary                   | 1.6.1        | cxlibrary-1.12.1-1.6.1.jar               | None                                     |
	| UCHIJAAAA | dynamiclights               | 1.4.6        | DynamicLights-1.12.1.jar                 | None                                     |
	| UCHIJAAAA | dynamiclights_onfire        | 1.0.7        | DynamicLights-1.12.1.jar                 | None                                     |
	| UCHIJAAAA | dynamiclights_creepers      | 1.0.6        | DynamicLights-1.12.1.jar                 | None                                     |
	| UCHIJAAAA | dynamiclights_dropitems     | 1.1.0        | DynamicLights-1.12.1.jar                 | None                                     |
	| UCHIJAAAA | dynamiclights_entityclasses | 1.0.1        | DynamicLights-1.12.1.jar                 | None                                     |
	| UCHIJAAAA | dynamiclights_mobequipment  | 1.1.0        | DynamicLights-1.12.1.jar                 | None                                     |
	| UCHIJAAAA | dynamiclights_flamearrows   | 1.0.1        | DynamicLights-1.12.1.jar                 | None                                     |
	| UCHIJAAAA | dynamiclights_floodlights   | 1.0.3        | DynamicLights-1.12.1.jar                 | None                                     |
	| UCHIJAAAA | dynamiclights_otherplayers  | 1.0.9        | DynamicLights-1.12.1.jar                 | None                                     |
	| UCHIJAAAA | dynamiclights_theplayer     | 1.1.3        | DynamicLights-1.12.1.jar                 | None                                     |
	| UCHIJAAAA | jei                         | 4.8.0.114    | jei_1.12.2-4.8.0.114.jar                 | None                                     |
	| UCHIJAAAA | easiervillagertrading       | 1.1.0        | easiervillagertrading-1.12-1.1.0.jar     | None                                     |
	| UCHIJAAAA | endmetals                   | 1.2.0-beta1  | EndMetals-1.12-1.2.0-beta1.5.jar         | None                                     |
	| UCHIJAAAA | fastleafdecay               | v14          | FastLeafDecay-v14.jar                    | None                                     |
	| UCHIJAAAA | cfm                         | 4.1.5        | furniture-4.1.5-1.12.jar                 | None                                     |
	| UCHIJAAAA | giacomos_fishing_net        | 1.6          | GiacomosFishingNet-1.12.2-1.6.jar        | None                                     |
	| UCHIJAAAA | infinitefluids              | 1.2.0        | infinitefluids-1.11-1.2.0.jar            | None                                     |
	| UCHIJAAAA | jehc                        | 1.3.1        | jehc-1.12-1.3.1.jar                      | None                                     |
	| UCHIJAAAA | journeymap                  | 1.12.2-5.5.2 | journeymap-1.12.2-5.5.2.jar              | None                                     |
	| UCHIJAAAA | levelup2                    | ${version}   | Level Up! 2-1.1.9-1.12.jar               | None                                     |
	| UCHIJAAAA | morefurnaces                | 1.10.4       | MoreFurnaces-1.12.2-1.10.4.jar           | None                                     |
	| UCHIJAAAA | nethermetals                | 1.2.0-beta1  | NetherMetals-1.12-1.2.0-beta1.15.jar     | None                                     |
	| UCHIJAAAA | orespawn                    | 3.2.0        | OreSpawn-1.12-3.2.0.95.jar               | None                                     |
	| UCHIJAAAA | harvestcraft                | 1.12.2a      | Pam's HarvestCraft 1.12.2a.jar           | None                                     |
	| UCHIJAAAA | roguelike                   | 1.8.0        | RoguelikeDungeons-1.12.2-1.8.0.jar       | None                                     |
	| UCHIJAAAA | ruins                       | 16.9         | Ruins-1.12.jar                           | None                                     |
	| UCHIJAAAA | simpleleather               | 1.12-1.0     | simpleleather-1.12-1.0.jar               | None                                     |
	| UCHIJAAAA | veinminermodsupport         | 0.38.1       | VeinMiner-1.12-0.38.1.639+134fb1e.jar    | None                                     |
	| UCHIJAAAA | villagermarket              | 1.0          | villagermarket-0.2-HF.jar                | None                                     |
	| UCHIJAAAA | waystones                   | 4.0.17       | Waystones_1.12.1-4.0.17.jar              | None                                     |

	Loaded coremods (and transformers): 
DLFMLCorePlugin (DynamicLights-1.12.1.jar)
  atomicstryker.dynamiclights.common.DLTransformer
CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  cubex2.cxlibrary.CoreModTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Timroham'/313, l='Townsville', x=-226.10, y=69.00, z=274.37]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_C6
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 388.13
	OpenGlRenderer: GeForce GTX 660/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
</details>`

**Comment by myrriad** [comment]
I've also gotten the error after using the market. BTW this is after I ate a cyclic inventory upgrade, however it still crashed even after I took everything out of it. 

Version: Enigmatica 2 Expert v1.37

Crash log: https://pastebin.com/1HGsfE1X

I also got a ConcurrentModificationException, but the stacktrace is different.

**Comment by faceofcat** [comment]
this is weird... both of this errors don't contain any of my code in the stack trace...

but it seems my mod somehow causes this... as it happens by using the market block.

I guess I will need to find a way to actually reproduce this in a debuggable environment... that might take some time... :(

**Comment by QUEWEX** [comment]
I've also received a crash when I went to use the market, to do a Max Sell transaction with a cleric villager, selling zombie flesh. My guess was that my inventory was actually full at the time, but on finding this error report, perhaps that was not the issue. However, my stack trace did reference VillagerMarketScreen, unlike those above, so perhaps this is a different error.

When I reloaded the game after the crash, I did receive the 7 emeralds in my inventory, with the requisite number of flesh removed.

Enigmatica 2 (normal) 1.47

[Crash log](https://pastebin.com/gcin5q4x)

**Comment by myrriad** [comment]
Actually, the cyclic inventory thing may not be related, as my inventory? i think was also full at the time.

**Comment by James-Fire** [comment]
I'm having this issue too. The launcher has your mod doing something in the first few lines of its report, but beyond that IDK. I have a crash log too, if you want it.

**Comment by James-Fire** [comment]
Now I got a crash when using the single sell button. I'll just collect my crash logs, if you want em let me know.

**Comment by faceofcat** [comment]
yes... please do.

I've been trying to make this happen a few times over the last months/year... never could.

seems to be a "random" thing... :(

so yeah... any logs would help...

thanks.

**Comment by James-Fire** [comment]
[crash-2018-11-24_16.44.16-client.txt](https://github.com/MinecraftModDevelopmentMods/Villager-Market/files/2612894/crash-2018-11-24_16.44.16-client.txt)
[crash-2018-11-24_16.52.05-client.txt](https://github.com/MinecraftModDevelopmentMods/Villager-Market/files/2612895/crash-2018-11-24_16.52.05-client.txt)
[crash-2018-11-25_00.11.02-server.txt](https://github.com/MinecraftModDevelopmentMods/Villager-Market/files/2612896/crash-2018-11-25_00.11.02-server.txt)
I've got three, from today no less.

The last one, the server side, does not say that your mod is the cause, but that is what I was doing at the time it crashed.

**Comment by James-Fire** [comment]
[crash-2018-11-25_12.56.33-server.txt](https://github.com/MinecraftModDevelopmentMods/Villager-Market/files/2613439/crash-2018-11-25_12.56.33-server.txt)
Have another one.

**Comment by James-Fire** [comment]
[crash-2018-11-25_16.39.43-server.txt](https://github.com/MinecraftModDevelopmentMods/Villager-Market/files/2613626/crash-2018-11-25_16.39.43-server.txt)
This one I was just scrolling through the market UI.

**Comment by James-Fire** [comment]
I reloaded after that crash, and it changed your market into 2 Steel slabs from BaseMetals.

Minecraft is drunk.
